command: ["streamlit", "run", "app/main.py", "--server.address", "0.0.0.0"]

env:
  - name: DATABRICKS_AUTH_TYPE
    value: "pat"

  - name: PYTHONPATH
    value: "."
    
  - name: WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: CATALOG
    value: "main"
  - name: SCHEMA
    value: "retail_gold"
  - name: TABLE
    value: "vw_sales_daily"

  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
