command: ["streamlit", "run", "app/main.py", "--server.address", "0.0.0.0"]

env:
  - name: PYTHONPATH
    value: "."
  - name: WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: CATALOG
    value: "main"
  - name: SCHEMA
    value: "retail"
  - name: TABLE
    value: "superstore_silver"

  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
